name: Build and Commit dist

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Commit dist folder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-build dist"
          file_pattern: dist/*
          skip_dirty_check: false
