name: Deploy Vite Website to Subdomain via SFTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy to Subdomain
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🛠️ Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📦 Install Dependencies
      run: npm install

    - name: 🛠️ Build Project
      run: npm run build

    - name: 🚀 Sync dist folder to Subdomain via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: ${{ secrets.FTP_SERVER }}
        ssh_port: 22                             # cPanel का डिफ़ॉल्ट SFTP पोर्ट
        local_path: ./dist/*                     # बिल्ड फोल्डर की सारी फाइलें
        remote_path: /home/goomozon/my.goomozon.shop/ # आपके सबडोमेन का असली पाथ
